# -*- coding: utf-8 -*-
"""ApiJsonfromCSV

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DYq4kYNP36yjU2YH6e0JIa2it5HSr6b5
"""

pip install panda

pip install flask

pip install flask_ngrok

# Formação Python Developer
# Criando uma API com Flask no Ambiente COLAB
# Desafio  proposto pelo módulo "Integração Com Python e Frameworks" da Digital Innovation One
# Autor: [Luis Pontes]
# Perfil DIO: [https://web.dio.me/users/MAILTOLUISCARLOS]
# GitHub: [https://github.com/CientistaPY]


import pandas as pd
from flask_ngrok import run_with_ngrok
from flask import Flask, jsonify

app = Flask(__name__)
run_with_ngrok(app)  # Para expor a API usando ngrok

# Fará com que o Pandas ignore as linhas que não podem ser analisadas corretamente e continue lendo o restante do arquivo
df = pd.read_csv(csv_url, error_bad_lines=False)
# URL do arquivo CSV no GitHub
csv_url = "https://github.com/CientistaPY/desafios_dio/blob/main/Forma%C3%A7%C3%A3o%20Python%20Developer/UtilizandoFrameworks/planilha.csv"

@app.route("/index")
def get_csv_as_json():
    try:
        # Lê o arquivo CSV do GitHub
        df = pd.read_csv(csv_url)
        # Converte o DataFrame para um formato JSON
        data_json = df.to_json(orient="records")
        return jsonify(data_json)
    except Exception as e:
        return jsonify({"error": str(e)})

if __name__ == "__main__":
    app.run()